name: imaging-python-course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - conda-forge::python
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision
  - conda-forge::ipykernel
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::seaborn
  - conda-forge::scipy
  - conda-forge::scikit-image
  - conda-forge::openpyxl
  - conda-forge::xmlschema
  - conda-forge::bioformats_jar
  - conda-forge::nd2
  - conda-forge::cellpose
  - conda-forge::statannotations
  - conda-forge::ipywidgets
  - conda-forge::mpl-interactions
  - conda-forge::trackpy
  - conda-forge::tifffile
  - conda-forge::readlif
  - conda-forge::napari
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-czi
    - bioio-lif
    - bioio-ome-tiff
    - bioio-tifffile

